# Generated by Django 3.2.9 on 2023-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=244)),
                ('short_name', models.CharField(max_length=244)),
                ('vessel_type', models.CharField(max_length=244)),
                ('built', models.IntegerField()),
                ('gt', models.IntegerField()),
                ('dwt', models.IntegerField()),
                ('size', models.CharField(max_length=244)),
                ('draft', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
